# Deployment definition file for python FastAPI sample application and NodePort service.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi_app
  template:
    metadata:
      labels:
        app: fastapi_app
    spec:
      containers:
      - name: my-con1
        image: harikrishnan/python-test  # Docker image that was pushed into my Docker registry.
        imagePullPolicy: Always      # Always pull the latest image from the registry.
        ports:
        - name: http
          containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi_app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30002  # Choose a port in the range 30000-32767 (or use "0" for a randomly allocated port)

