# sonarqube-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: NodePort
  selector:
    app: sonarqube-server  # Make sure this label matches the one used in the SonarQube deployment
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30000  # Choose any available port number in the range 30000-32767

